### ISSUE TITLE
Permit localization in any language

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/grey-handling#12]
In order to be able to do #11 we need to add localization for all string first.

**Comment by swetlover** [comment]
Has the localization project been cancelled?

**Comment by Pierre-Sassoulas** [comment]
Thank you for keeping track of this. 

No, I'm still planning on doing it. But I'm still changing text and adding text often at the moment. I want to have something relatively stable in other parts of the code first because I can't update localization myself. I don't want to ask for minor modifications in localizations string too much.

**Comment by Pierre-Sassoulas** [comment]
Hi @swetlover , as the addon is relatively stable now, I made a first draft for the addon localization. It should permit to create a Chinese localization easily for #11 .

What you can do to get started is copy-paste everything between `if GetLocale() == "frFR" then` and `end` in `localization/fr.lua` in `localization/zh.lua` between `if GetLocale() == "zhTW"` and `end` and replace the french strings by the proper Chinese translation. You can check that it's working by launching the game and checking that the string are what you would expect.

Let me know if you have any question and thanks again for proposing your help!
