### ISSUE TITLE
Localize the addon in french

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/grey-handling#13]
Permit to test myself if #12 work before asking for someone help in a language I do not know.

**Comment by Xatrith** [comment]
Ask for this language if you need. I'm from France ^^

**Comment by Pierre-Sassoulas** [comment]
Done in https://github.com/Pierre-Sassoulas/grey-handling/commit/aa0c366ca9748260ab1b879c57f257b6dfa784a2
