### ISSUE TITLE
EU English it saying that it has problem with my localization and that language is "Chinese?"

### ISSUE THREAD

**Issue by Larsy93** [Pierre-Sassoulas/grey-handling#14]
EU English it saying that it has problem with my localization and that language is "Chinese?"

**Comment by Pierre-Sassoulas** [comment]
Please update the addon to the last version, this was a problem with item not being in the cache, the message should become "You don't have any '[beef jerky]' right now, so even if it was looted by Teammate-TeammateServer, we can't ask the WOW API about it yet.".

**Comment by Pierre-Sassoulas** [comment]
I'm closing fast, but thank you for the report much appreciated. I'd rather have that than no feedback.

**Comment by Pierre-Sassoulas** [comment]
This is really fixed in 0.7.0, it was caused by #15. So you should update yet again (sorry :)).
