### ISSUE TITLE
This addon seems to hijack the print() function

### ISSUE THREAD

**Issue by thefuzzy0ne** [Pierre-Sassoulas/grey-handling#22]
With an addon I am working on, I was trying to debug a chat filter . After about 2 hours of not getting the output I was expecting, I disabled Grey Handling (as I noticed the name pop up a lot in chat when it shouldn't) and I finally got the output I was expecting.

This addon seems to cause lots of problems when trying to print to a chat frame using `print`. It seems to gobble up everything after the first argument to print. Just running `/run print("test")` outputs `GreyHandling: test` to the chat frame. GreyHandling should **not** be intercepting these calls.

**Comment by Pierre-Sassoulas** [comment]
Ho, sorry I thought it was doing this only in my local context. I'm going to fix it ASAP. Thanks for the report !

**Comment by Pierre-Sassoulas** [comment]
Should be fixed if you upgrade to `0.9.2c`. I'm really sorry about the debug you had to do, I thought that the open-closed principle was enforced somewhere by LUA or Wow and evidently, it is not.

**Comment by thefuzzy0ne** [comment]
Hey, no problem. Shit happens. Thanks for sorting it out so quickly. :-)
