### ISSUE TITLE
Automatic exchanges within-groups to optimize the group's bag space

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/grey-handling#3]
Ie "Give me two fangs, I'll give you 5 broken eggs so we have one more bag space each", but industrialized.

**Comment by Pierre-Sassoulas** [comment]
Implemented suggestion for exchange in 0.4.0.

**Comment by Xatrith** [comment]
Hi ! We are currently testing this feature with a friend, and we noticed two things :

It would be a lot more effective if it could calculate more than 1v1 exchanges.

It seems to bug a bit after the first trade as it doesn't register the Light feather moving from one char to the other.

**Comment by Pierre-Sassoulas** [comment]
Thank you for testing the addon, and for particpating on github, really appreciated.

Yes, right now the suggestion are what you could do yourself looking at what you can see in the group chat. So if someone throws something, exchanges something or sell something you can't know what they did (likewise the "internal knowledge" of the addon is deprecated and the suggestions start to suck).

I could add the exchange tracking but this will never be perfect. And with at least two persons having the addon things start to get more interesting because the addons can communicate together and have perfect knowledge of the bag content for all players with the addon. And do some really useful suggestions based on that. Also, what is junk for you could be someone else treasure, if scrap is properly configured, so I think this could become really powerful.

Unfortunately, there were a lot of bugs to prioritze before that. So it's not done yet, but it seem feasible and I already designed the basics. The choice of the best suggestion could also be made a lot better, but I'll do the linear algebra at the end ;)

**Comment by Xatrith** [comment]
I could manage to convince my friend to install the add on too when we play together again ^^ Would be glad to test this :)

**Comment by Pierre-Sassoulas** [comment]
There is a beta version available if both you and your teammate install 0.8.1c. Thank you for your offer to test this, I would love to have some feedback. Right now the "best" exchange is not super clever, I just try to limit the amount of money that needs to be exchanged, this is the next thing I'm going to make better. I suggest that you loot at the item your teammate have yourself in your bag in the meantime.
