### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by Jinnai** [Pierre-Sassoulas/grey-handling#36]
I see this was already fixed in a recent commit but please publish a new version asap as the current version is practically unusable with the chat spam (Calculated cheapest object).

**Comment by Pierre-Sassoulas** [comment]
Ho sorry, my bad. Yeah it must have spammed the hell out of your chat in the current state ! Thank you for  opening this issue really quickly, thanks to you there is only 24 people affected.  I hot fixed it in 1.7.6 and hopefully next version is going to be a lot faster. (I removed most useless calculation, but I need to figure out how to update when the scrap or peddler list of junk is modified before releasing).
