### ISSUE TITLE
Make glowing work with ArkInventory

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/grey-handling#7]
Right now we have a permanent white glow used for action suggestion by Blizzard. Everything happens in the [`SetBagItemGlow` function](
https://github.com/Pierre-Sassoulas/grey-handling/blob/master/functions/SetBagItemGlow.lua#L4), where we need to better get the item for arkinventory.

We had some help from the arkinventory maintainer here : 
https://github.com/arkayenro/arkinventory/issues/1193#issuecomment-523785016

**Comment by Pierre-Sassoulas** [comment]
The temporary glow only works with wow retail.

**Comment by Xatrith** [comment]
Hello,

Not sure you've seen this, but the current glow is permanent and not temporary.

Xatrith

**Comment by Pierre-Sassoulas** [comment]
I'm aware but this is a low priority enhancement right now because you can remove the glow by relaunching when there is no grey left.

**Comment by Pierre-Sassoulas** [comment]
The glow is permanent and never removed unless you reload on classic, that's an annoying bug especially because when you reload you loose your teammate's bag content information.
