### ISSUE TITLE
Adding a list of junk considered like grey items

### ISSUE THREAD

**Issue by Xatrith** [Pierre-Sassoulas/grey-handling#8]
Hi ! 

First thx for your add on, it's really nice to have. I would like to make a feature suggestion because it has happened to me quite often that the lowest priced item is actually not a grey but an other item like a consumable. Would it be possible to allow players to manually add items to the pool of items they want the add on to consider as trash ?

Anyway thx for your work :)

Xatrith

**Comment by Pierre-Sassoulas** [comment]
Happened to me too (well 20mn ago to be exact), this is a nice suggestion. I'll try to implement it if the queue is too high :D

**Comment by Pierre-Sassoulas** [comment]
Do you have "Scrap Junk seller" installed? Apparently, they have a smart list of junk, I could try to integrate with it.

**Comment by Xatrith** [comment]
Yes I do, but if you want me to test something it will have to wait until tonight when I come back from work ^^

**Comment by Pierre-Sassoulas** [comment]
Don't worry I can test it myself :)

**Comment by Xatrith** [comment]
Ok :) and BTW, great way to use the time spent in queues :p

**Comment by Pierre-Sassoulas** [comment]
This was a lot easier than I thought it would be. Let me know if it works for you after upgrading to 0.6.0.

**Comment by Xatrith** [comment]
It works fine so far. Not wanting to deny their work or yours, but Scaps does not allow to manually add an item to the junk list. Maybe by modifying the list directly in the add on files ?

**Comment by Pierre-Sassoulas** [comment]
I did not use Scrap a lot until now but if you go in options there is some that you might find interesting. The one that would probably work for all cases are "unusable equipment = junk", and "smart learning". If I understand correctly scrap can learn what is your junk list after you sell something to a vendor a lot (or if you just drop it in the scrap logo at a vendor).

Seem to be confirmed by what I see [here](https://www.mmo-champion.com/threads/1779485-Scrap-addon-help)  : 

>  you *can* do out of the box is to drop an item onto the "sell junk" button at a vendor, which will toggle the junk/useful status directly. My mode of operation for exactly the problem you highlight is to (a) use auto-learning, and (b) use the drop-on-"sell junk"-button trick for things that I have lots of, or see frequently, and that have not auto-learned yet.

**Comment by Xatrith** [comment]
Ho nice, you found out how to add items to the empty lists i saw, thx a lot. And for the smart learning, be carefull. If you have an item you keep only say 1 stack in your inventory and sell the rest, he might learn that you sell it but will not keep the quantity. With that it should be fine, it will not work for white items but this problem should wash out as they disappear from the loot tables.

Thx a lot for your help !

**Comment by Pierre-Sassoulas** [comment]
I think the best to do is to disable smart learning and to define a keyboard shortcut in order to add an item to scrap list with Escape then shortcut, then addon, then scrap. So if you encounter an item for the first time you can add it directly by hovering + shortcut while not at a vendor. (I read the scrap tutorial that happens to be surprisingly important and useful :D)

**Comment by Xatrith** [comment]
You're a mine of good informations :) Seems like using google to search was not the way to go :p
